name: PhysioSenseTS
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas
  - scipy=1.11.4
  - matplotlib

  - scikit-learn
  - xgboost
  - pytorch

  - jupyterlab
  - pip:
     - -r requirements.txt
